import React from 'react';
import { Card, CardContent } from '@/components/ui/card';

export default function HowItWorksPage() {
    const invest = [
        {
          title: 'Explore Franchises',
          description: 'Browse verified franchise projects across industries — food, retail, fitness, and more.'
        },
        {
          title: 'Check Details & ROI',
          description: 'View investment amount, expected returns, location, and business performance metrics.'
        },
        {
          title: 'Choose Investment Amount',
          description: 'Decide how much you want to invest — starting from $1 per share.'
        },
        {
          title: 'Buy Franchise Tokens',
          description: 'Complete payment using your wallet; your ownership is recorded instantly on the blockchain.'
        },
        {
          title: 'Track in Your Dashboard',
          description: 'Monitor your token holdings, project updates, and franchise stage (Fundraising, Launching, Operational).'
        },
        {
          title: 'Receive Monthly Earnings',
          description: 'Get automatic revenue share payouts based on your token percentage directly to your wallet.'
        }
      ];
      const register = [
        {
          title: 'Sign Up as a Brand Owner',
          description: 'Create your business account and verify your brand.'
        },
        {
          title: 'Build Brand Profile',
          description: 'Add your logo, brand story, industry, and contact information for investors.'
        },
        {
          title: 'Create Franchise Listing',
          description: 'Define total investment, space requirement, setup cost, and franchise fee details.'
        },
        {
          title: 'Select Franchise Locations',
          description: 'Pin available or desired areas on the map where you want to expand.'
        },
        {
          title: 'Tokenize Your Franchise',
          description: 'Franchiseen converts your franchise into digital ownership tokens as investment.'
        },
        {
          title: 'Publish & Go Live',
          description: 'Once verified, your franchise becomes visible on the platform for investors to fund and own.'
        }
      ];
      const funding = [
        {
          title: 'Tokenize the Franchise',
          description: 'The total investment needed is represented as total token supply, each token valued at $1 per share.'
        },
        {
          title: 'Receive Qualified Leads',
          description: 'Investors buy tokens during the fundraising stage, contributing directly via secure wallets.'
        },
        {
          title: 'Review & Approve Leads',
          description: 'All collected funds remain safely locked in a blockchain escrow account until the goal is fully met.'
        },
        {
          title: 'Collect Funds Securely',
          description: 'Once fully funded, the escrow releases funds — Franchise Capital → Franchise wallet. Fee & Step → Brand wallet'
        },
        {
          title: 'Track in Your Dashboard',
          description: 'The franchise moves from Fundraising to Launching stage — setup begins, vendors are paid, and operations start.'
        },
        {
          title: 'Receive Monthly Earnings',
          description: 'After launch, revenue generated by the franchise is distributed as payouts to all token holders.'
        }
      ];
      const payouts = [
        {
          title: 'Access Franchise Dashboard',
          description: 'Track investments, sales performance, and investor ownership in one unified dashboard.'
        },
        {
          title: 'Sync POS Revenue Data',
          description: 'Revenue updates from your franchise POS to record verified sales and profit reports.'
        },
        {
          title: 'Automate Profit Calculations',
          description: 'Smart contracts automatically calculate revenue shares based on tokenized ownership.'
        },
        {
          title: 'Distribute Earnings to Investors',
          description: 'Payouts are processed in USDT, sent directly to investor wallets based on franchise earnings.'
        },
        {
          title: 'Manage Team & Reports',
          description: 'Brands and franchisees can manage finances, upload statements, and communicate directly with investors.'
        },
        {
          title: 'Transparent On-Chain Records',
          description: 'Every transaction — from funding to payout — is recorded on the blockchain, ensuring 100% trust and traceability.'
        }
      ];

  return (
    <div>
        <div className="bg-stone-800 py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-6">
            <h1 className="text-4xl md:text-6xl font-bold text-white mb-6">
            How Franchiseen Works
            </h1>
            <p className="text-xl text-stone-400 mb-8 max-w-4xl mx-auto">
              Franchiseen is a platform that allows you to invest in franchises and earn money from them.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mt-16">
            <div className="text-center">
              <div className="w-16 h-16 bg-stone-100 font-bold text-xl dark:bg-stone-700/30 rounded-full flex items-center justify-center mx-auto mb-4">
                1
              </div>
              <h3 className="text-lg font-semibold text-white mb-2">Invest & Earn</h3>
              <p className="text-stone-400 text-sm">How to buy franchise token and <br /> earn from it</p>
            </div>
            <div className="text-center">
            <div className="w-16 h-16 bg-stone-100 font-bold text-xl dark:bg-stone-700/30 rounded-full flex items-center justify-center mx-auto mb-4">
                2
              </div>
              <h3 className="text-lg font-semibold text-white mb-2">Register & Create</h3>
              <p className="text-stone-400 text-sm">How to register brands and <br /> create a franchise</p>
            </div>

            <div className="text-center">
                <div className="w-16 h-16 bg-stone-100 font-bold text-xl dark:bg-stone-700/30 rounded-full flex items-center justify-center mx-auto mb-4">
                    3
                </div>
              <h3 className="text-lg font-semibold text-white mb-2">Funding & Launching</h3>
              <p className="text-stone-400 text-sm">How you can get funding and <br /> launch a franchise</p>
            </div>

            <div className="text-center">
                <div className="w-16 h-16 bg-stone-100 font-bold text-xl dark:bg-stone-700/30 rounded-full flex items-center justify-center mx-auto mb-4">
                4
              </div>
              <h3 className="text-lg font-semibold text-white mb-2">Manage & Payouts</h3>
              <p className="text-stone-400 text-sm">How you can manage and <br /> distribute payouts for your franchise</p>
            </div>
          </div>
        </div>
      </div>
      {/* Values Section */}
      <div className="py-20 bg-yellow-50/50 dark:bg-stone-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
          <div className="w-16 h-16 bg-stone-800 font-bold text-xl text-white dark:bg-stone-700/30 rounded-full flex items-center justify-center mx-auto mb-4">
                1
              </div>
            <h2 className="text-3xl font-bold text-stone-900 dark:text-white mb-4">
            Invest & Earn
            </h2>
            <p className="text-xl text-stone-600 dark:text-stone-300 max-w-3xl mx-auto">
            How to buy franchise token and earn from it
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {invest.map((value, index) => (
              <Card key={index} className="bg-white dark:bg-stone-800/50">
                <CardContent className="p-6 text-center">
                  <h3 className="text-xl font-semibold text-stone-900 dark:text-white mb-3">{value.title}</h3>
                  <p className="text-stone-600 dark:text-stone-300">{value.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </div>
      {/* Values Section */}
      <div className="py-20 bg-yellow-50/50 dark:bg-stone-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <div className="w-16 h-16 bg-stone-800 font-bold text-xl text-white dark:bg-stone-700/30 rounded-full flex items-center justify-center mx-auto mb-4">
                2
              </div>
            <h2 className="text-3xl font-bold text-stone-900 dark:text-white mb-4">
            Register & Create
            </h2>
            <p className="text-xl text-stone-600 dark:text-stone-300 max-w-3xl mx-auto">
            How to register brands and create a franchise
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {register.map((value, index) => (
              <Card key={index} className="bg-white dark:bg-stone-800/50">
                <CardContent className="p-6 text-center">
                  <h3 className="text-xl font-semibold text-stone-900 dark:text-white mb-3">{value.title}</h3>
                  <p className="text-stone-600 dark:text-stone-300">{value.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </div>
      {/* Values Section */}
      <div className="py-20 bg-yellow-50/50 dark:bg-stone-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
          <div className="w-16 h-16 bg-stone-800 font-bold text-xl text-white dark:bg-stone-700/30 rounded-full flex items-center justify-center mx-auto mb-4">
                3
              </div>
            <h2 className="text-3xl font-bold text-stone-900 dark:text-white mb-4">
            Funding & Launching
            </h2>
            <p className="text-xl text-stone-600 dark:text-stone-300 max-w-3xl mx-auto">
            How you can get funding and launch a franchise
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {funding.map((value, index) => (
              <Card key={index} className="bg-white dark:bg-stone-800/50">
                <CardContent className="p-6 text-center">
                  <h3 className="text-xl font-semibold text-stone-900 dark:text-white mb-3">{value.title}</h3>
                  <p className="text-stone-600 dark:text-stone-300">{value.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </div>
      {/* Values Section */}
      <div className="py-20 bg-yellow-50/50 dark:bg-stone-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
          <div className="w-16 h-16 bg-stone-800 font-bold text-xl text-white dark:bg-stone-700/30 rounded-full flex items-center justify-center mx-auto mb-4">
                4
              </div>
            <h2 className="text-3xl font-bold text-stone-900 dark:text-white mb-4">
            Manage & Payouts
            </h2>
            <p className="text-xl text-stone-600 dark:text-stone-300 max-w-3xl mx-auto">
            How you can manage and distribute payouts for your franchise
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {payouts.map((value, index) => (
              <Card key={index} className="bg-white dark:bg-stone-800/50">
                <CardContent className="p-6 text-center">
                  <h3 className="text-xl font-semibold text-stone-900 dark:text-white mb-3">{value.title}</h3>
                  <p className="text-stone-600 dark:text-stone-300">{value.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
